services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Backend\:
    resource: '../Classes/*'

  TYPO3\CMS\Backend\Command\LockBackendCommand:
    tags:
      - { name: 'console.command', command: 'backend:lock' }

  TYPO3\CMS\Backend\Command\UnlockBackendCommand:
    tags:
      - { name: 'console.command', command: 'backend:unlock' }

  TYPO3\CMS\Backend\Command\ReferenceIndexUpdateCommand:
    tags:
      - { name: 'console.command', command: 'referenceindex:update' }

  TYPO3\CMS\Backend\Command\ResetPasswordCommand:
    tags:
      - { name: 'console.command', command: 'backend:resetpassword', schedulable: false }

  TYPO3\CMS\Backend\Template\ModuleTemplate:
    shared: false
    public: true

  TYPO3\CMS\Backend\Controller\File\ImageProcessController:
    shared: false
    public: true

  TYPO3\CMS\Backend\View\PageLayoutView:
    shared: false
    public: true

  TYPO3\CMS\Backend\History\RecordHistoryRollback:
    public: true

  TYPO3\CMS\Backend\Backend\Shortcut\ShortcutRepository:
    public: true

  TYPO3\CMS\Backend\Controller\AboutController:
    tags: ['backend.controller']

  TYPO3\CMS\Backend\Controller\EditDocumentController:
    tags: ['backend.controller']

  TYPO3\CMS\Backend\Controller\LoginController:
    tags: ['backend.controller']

  TYPO3\CMS\Backend\Controller\HelpController:
    tags: ['backend.controller']

  TYPO3\CMS\Backend\Form\FormDataProvider\SiteDatabaseEditRow:
    public: true

  # Category security checks for backend users
  TYPO3\CMS\Backend\Security\CategoryPermissionsAspect:
    tags:
      - name: event.listener
        identifier: 'backend-user-permissions'
        method: 'addUserPermissionsToCategoryTreeData'
        event: TYPO3\CMS\Core\Tree\Event\ModifyTreeDataEvent

  # Listener to provide information about column without a colPos set
  TYPO3\CMS\Backend\View\PageLayoutViewDrawEmptyColposContent:
    tags:
      - name: event.listener
        identifier: 'backend-empty-colpos'
        event:  TYPO3\CMS\Backend\View\Event\AfterSectionMarkupGeneratedEvent
